### PR TITLE
fix/smaller screens

### PR DESCRIPTION
**Pull request by KngZhi**
- fix: align tooltip padding
- feat: nowrap
- feat: vertical scroll on MarketDetails
- feat: add margin while less than xl

## Related issue
- #1024

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/11361147/182017366-68ed59c0-04f0-4197-ab2b-93ea5f6ed144.mov

### CODE REVIEW

**Comment by platschi** [comment]
Thanks! Scrolling vertically on smaller screens works fine! A few things:

1) Tooltips on Firefox are still way off, while they do work fine on Chrome.

2) On Firefox, the `MarketDetails` now scrolls horizontal, too. This seems to be a Firefox related flexbox bug and could be mitigated by removing the set height of 55px. Not sure if this affects the box otherwise, though. Chrome seems unaffected of this bug.

@asherism might have a better understanding of the issues at hand.

**Comment by asherism** [comment]
> 2\. On Firefox, the `MarketDetails` now scrolls horizontal, too. This seems to be a Firefox related flexbox bug and could be mitigated by removing the set height of 55px. Not sure if this affects the box otherwise, though. Chrome seems unaffected of this bug.

i'm confused- we want it to scroll horizontally, no?

**Comment by KngZhi** [comment]
On Firefox:

image

**Review by platschi — APPROVED** [review]
Thanks, fixes works fine now on both Chrome and Firefox!

**Comment by platschi** [comment]
> > 2. On Firefox, the `MarketDetails` now scrolls horizontal, too. This seems to be a Firefox related flexbox bug and could be mitigated by removing the set height of 55px. Not sure if this affects the box otherwise, though. Chrome seems unaffected of this bug.
> 
> i'm confused- we want it to scroll horizontally, no?

Yeah, I mixed up horizontal and vertical in my comment. Looks like it's all working fine now.

**Review by LeifuChen — APPROVED** [review]
@Junwei#7322 The root cause of this issue is that, in Chrome, the `fixed` position element (tooltip in our case) is relative to the viewport (browser window) while, in Firefox, the `fixed` position element is relative to the parent element (e.g. `MarketDetailContainer`). 

One possible solution is setting a new stacking context to make the `fixed` position element in Chrome relative to the parent element too. 

e.g.
image

I don't think it's better than your solution so let's keep your solution then.

**Pull request merged**
