### PR TITLE
Use subgraph codegen

### PR DESCRIPTION
**Pull request by Tburm**
Use codegen subgraphs to get around 1000 record limits. These changes include removing a lot of old/stale/unused code that was causing issues since I changed some types.

## Description
* Fetch trade counts and volumes using a generated subgraph
* Fetch candles using a generated subgraph
* Deletes old components and files in the `exchange` section. These are mostly related to showing candle data, which we don't do on the exchange page now.

## Issue
#772 

## Motivation and Context
The 1000 record limitation makes our "24H Trades" value inaccurate since the data is limited:
image

Additionally, our candle data fails when trying to fill gaps on low intervals given the number of candles it is fetching at a time:
image

To replicate:
* Maximize screen size
* Set candles to 15m
* Zoom out as much as possible
* Set candles to 1m

### CODE REVIEW

**Comment by Tburm** [comment]
@platschi I found a bug when you switch markets, this one is not quite ready for review yet.

**Comment by Tburm** [comment]
@platschi this is fixed, ready for review

**Comment by platschi** [comment]
@Tburm Works great, charts work smooth. 

Only one lint warning and conflicts to be resolved, and we're ready to go with this PR

**Comment by Tburm** [comment]
@platschi This is ready to test again.

**Review by platschi — APPROVED** [review]

**Pull request merged**
