### PR TITLE
Fix: UI enhancement on L1.

### LINKED ISSUE #883: UI Improvements on L1
### Subject of the issue
The current `v2` website, when connected to Ethereum L1, can be significantly improved and cleaned up. E.g. Futures Markets are not available on L1, so they should not be available. Several items for improvement to be listed below:

### Deliverables

**Important**: When refactoring the code, keep in mind that we might add more networks in the future with different conditions, so the code should already take this into account and be flexible in this sense.

When switching/connected to L1 (or any other network not being Optimism Mainnet or Optimistic Kovan):
- [x] hide Futures & Leaderboard in nav bar
- [x] hide Futures Positions & Futures Markets on Dashboard
- [x] hide Futures Markets in "Markets" tab (dashboard) and default to Spot
- [x] hide accessible margin (Futures markets) in sUSD modal
- [x] Show a CTA "Switch to L2 to access Perpetual Futures" on the Dashboard (design tbd, contact devDAO PM)

### Rewards
150 SNX

### PR DESCRIPTION
**Pull request by zhyd1997**
Closes #883 

## Description

When switching/connected to L1 (or any other network not being Optimism Mainnet or Optimistic Kovan):
- [x]  hide Futures & Leaderboard in nav bar
- [x] hide Futures Positions & Futures Markets on Dashboard
- [x] hide Futures Markets in "Markets" tab (dashboard) and default to Spot
- [x] hide accessible margin (Futures markets) in sUSD modal
- [x]  Show a CTA "Switch to L2 to access Perpetual Futures" on the Dashboard (design tbd, contact devDAO PM)

## Related issue

#883 

## Motivation and Context

When refactoring the code, keep in mind that we might add more networks in the future with different conditions, so the code should already take this into account and be flexible in this sense.

### CODE REVIEW

**Comment by zhyd1997** [comment]
Something needs to be done:

-[ ] clear the console error:
allMarketSummaries

**Comment by 0xwontonsoup** [comment]
> Something needs to be done:
> 
> -[ ] clear the console error: allMarketSummaries

i think you would only receive that error if your wallet is not properly connected

**Comment by zhyd1997** [comment]
> > Something needs to be done:
> > -[ ] clear the console error: allMarketSummaries
> 
> i think you would only receive that error if your wallet is not properly connected

Reconnect exactly, IDK if it's my PR change problem.

**Review by Tburm — COMMENTED** [review]
The code here all looks good. I'd be happy to merge based on that, however I have some issues with the design choices here...

* If someone is connected to the wrong network (Arbitrum) there is almost no way for them to tell we _have_ Futures markets outside of the "Switch" buttons.
* I think users should be able to access the "Futures" page when not connected, because this could drive people to WANT to use our markets. The CTAs here don't catch my eye and draw me in that direction
* We should show high-level information about these markets if possible instead of hiding the information on the dashboard. Seeing open interest, volume, price is important if I'm evaluating platforms where I want to trade, and wallet connection shouldn't necessarily be required to make this decision.

@platschi How do you think we should handle this? I think these changes are ready as stated in the devDAO ticket requirements, but I'd prefer to make some additional changes before releasing this.

**Comment by platschi** [comment]
Thanks! Code is correct however we afterwards decided this needs to be addressed differently. Will keep this for future reference.

**Pull request closed without merging**
