### PR TITLE
Display futures position on chart

### PR DESCRIPTION
**Pull request by avclarke**
Show futures position entry and liquidation price on Trading view chart

## Related issue
https://github.com/Kwenta/kwenta/issues/693

## Motivation and Context
Enable a user to reference their current position as they view the chart or see a potential position as they edit position size

## Screenshots:
When inputting a potential position it shows a dashed line
[Image from Gyazo](https://gyazo.com/14f5eca36c37662493e6f48886ddf527)

When the position is live it displays solid lines
Screenshot 2022-04-25 at 09 45 42

### CODE REVIEW

**Review by koredefashokun — APPROVED** [review]

**Comment by koredefashokun** [comment]
The changes look good. Only small thing is we might want to use `colors.common.primaryRed` instead of `colors.red`.

**Review by platschi — APPROVED** [review]

**Comment by platschi** [comment]
@avclarke  Latest changes look good. However, on the [vercel deploy](https://kwenta-gex53h4sg-kwenta.vercel.app/market/sETH), looking e.g. at the ETH-PERP chart, it now keeps resetting the chart every 10 seconds or so.

**Comment by avclarke** [comment]
> @avclarke Latest changes look good. However, on the [vercel deploy](https://kwenta-gex53h4sg-kwenta.vercel.app/market/sETH), looking e.g. at the ETH-PERP chart, it now keeps resetting the chart every 10 seconds or so.

Ah yea I can see the issue now where the chart is being destroyed and recreated. Will get that fixed.

**Comment by avclarke** [comment]
Also noticing the position doesn't get cleared from the chart when you close it, going to look into that.

**Comment by avclarke** [comment]
Fixed previous issues and added the lines for potential position in addition to live position.

**Review by koredefashokun — DISMISSED** [review]

**Comment by platschi** [comment]
When I'm on a market, and switch the TV candles from 1h to 1d, I receive an unexpected error crash

**Comment by avclarke** [comment]
> When I'm on a market, and switch the TV candles from 1h to 1d, I receive an unexpected error crash

Seems related to trying to draw the lines before the data finished loading, now waiting for a callback from dataReady.

**Comment by Tburm** [comment]
What is the expected behavior when we have a position open? When I have no position, it works as expected drawing the entry price and liquidation prices on the chart.

When I have a position open, it displays my fixed entry point/liquidation prices when modifying my position.

Also @platschi We should think about adding a "settings" row above the chart so we can give users some flexibility on what is shown on the chart. This would include a checkbox to turn on/off these indicators, and eventually allow users to switch price feeds.

**Comment by avclarke** [comment]
@platschi @Tburm Should we remove the fixed entry lines when modifying a position and show adjusted potential position as the dashed line? Rather than show existing position and potential modified position at the same time?

**Comment by Tburm** [comment]
@avclarke That's what I would expect, that the "modifying position" stuff would overwrite the "current position stuff" while there are inputs.

**Comment by Tburm** [comment]
@avclarke I've also done some work on TV queries in [this PR](https://github.com/Kwenta/kwenta/pull/782), we may end up running into conflicts

**Pull request closed without merging**
