### PR TITLE
Competition Leaderboard

### PR DESCRIPTION
**Pull request by Tburm**
Building out the competition leaderboard for the upcoming mobile competition

## Description
* Split `Leaderboard` component up
* Add a component for each table
* Add competition filters to leaderboard
* Read competition data from IPFS files

## Related issue
- #820 

## Motivation and Context
Upcoming mobile competition

### CODE REVIEW

**Comment by platschi** [comment]
Looks good already. Some notes:

- [ ] ENS names are not fetched for tier leaderboard

**Comment by Tburm** [comment]
@platschi I'm aware ENS isn't done yet, I have to rearrange how we fetch some of this to make sure we can get ENS from any leaderboard without requesting it multiple times.

**Comment by platschi** [comment]
Note: Before merging this, we should merge #1241 and add the banner to the leaderboard page, too.

**Comment by platschi** [comment]
Todo:

- [ ] Add competition leaderboard to dashboard
- [ ] Add a way to show the current connected wallets level and rank on leaderboard

**Review by koredefashokun — APPROVED** [review]

**Pull request merged**
