### PR TITLE
hotfix: used suggestedDecimals only for asset prices.

### PR DESCRIPTION
**Pull request by zhyd1997**
## Related issue

Fixes: #1698 

## Screenshots (if appropriate):
Screen Shot 2022-12-01 at 06 01 31

`/market` page:
Screen Shot 2022-12-01 at 09 25 21
Screen Shot 2022-12-01 at 09 26 01
Screen Shot 2022-12-01 at 09 26 32
Screen Shot 2022-12-01 at 09 26 55
Screen Shot 2022-12-01 at 09 28 31
Screen Shot 2022-12-01 at 09 29 36

`/dashboard` page:
Screen Shot 2022-12-01 at 09 58 37

### CODE REVIEW

**Comment by platschi** [comment]
Here two decimals are also sufficient:

Screenshot 2022-12-01 at 10 55 37

**Comment by zhyd1997** [comment]
Hey @platschi 

This is default behavior, and I never changed it, you can see it on production website, when you enter the margin, it will be shrink to 2 decimals.

**Review by avclarke — APPROVED** [review]
Looks good!

**Review by LeifuChen — APPROVED** [review]
Looks good to me. Thanks for the contribution.

**Pull request merged**
