### PR TITLE
Get local date formatting string from browser

### PR DESCRIPTION
**Pull request by Xiaolei-Shawn**
## Description

When formatting dateTime presentation, call `getLocale` function to compute local dateTime formatting string, e.g.
- enUS: MM/dd/yyyy
- zhCN: yy-mm-dd
- etc

## Related issue

https://github.com/Kwenta/kwenta/issues/1484

## Motivation and Context

All displayed dates/times on Kwenta are displayed using a format local to the user.

## Screenshots (if appropriate):
Take example on futures transfer table
- zhCN
Screenshot 2022-11-07 at 21 02 33
- enUs
Screenshot 2022-11-07 at 21 02 20

### CODE REVIEW

**Review by Tburm — CHANGES_REQUESTED** [review]
It doesn't look like this function is actually implemented anywhere in the app. Most time is displayed using this component: https://github.com/Kwenta/kwenta/blob/a19d281bb4eb556312e69da1a2f9179d7edc5338/sections/futures/Trades/TimeDisplay.tsx#L24

To check you should look at time displayed on the following:
* Dashboard history (Dashboard -> History)
* Futures history (Futures -> "Trades" tab)

**Comment by Xiaolei-Shawn** [comment]
> It doesn't look like this function is actually implemented anywhere in the app. Most time is displayed using this component:
> 
> [kwenta/sections/futures/Trades/TimeDisplay.tsx](https://github.com/Kwenta/kwenta/blob/a19d281bb4eb556312e69da1a2f9179d7edc5338/sections/futures/Trades/TimeDisplay.tsx#L24)

Sorry, I don't quite follow your comment. Which function are you referring to? `getLocale()`? Could you elaborate a bit?
The idea is to figure out datTime formatting string based on result of `getLocale()`.

**Comment by Tburm** [comment]
@Xiaolei-Shawn Check the example in the description of this issue. It shows how the dates would display based on locale. Here's an example on the "trades" table:
image

This table would show the date based on the local format, but on your branch it will always display this time format.

I was referring to the `formatTxTimestamp` function in my comment. You edited this function, but this function is not implemented to actually format dates/timestamps in the app. You will need to find the functions that format these dates and add locale to those functions.

**Comment by Xiaolei-Shawn** [comment]
@Tburm, the function I updated is actually `timePresentation` but `formatTxTimestamp`. It's used by `Transfer` to format date.
https://github.com/Kwenta/kwenta/blob/fa2fa287c9e3693b2e5facc3312db876b4f799d2/utils/formatters/date.ts#L32

Thank you for pointing out about date/time formatting on `Trade`. It's missed by me and I will push changes to also use `getLocale` to resolve correct format.

**Review by Tburm — APPROVED** [review]
I see your changes, I think the `TimeDisplay` changes did it. I am seeing the proper date format on futures history, spot history, transfers, and trades tables. Great work!

**Pull request merged**
