### PR TITLE
New futures markets

### PR DESCRIPTION
**Pull request by koredefashokun**
## Description
This PR cleans up instances of the new futures markets on `v2`. It adds icons and fixes issues with truncated names, on the markets and positions tables, as well as the markets dropdown.

## Related issue
N/A

## Motivation and Context
This PR prepares for the launch of new futures markets on mainnet.

## How Has This Been Tested?
N/A

## Screenshots (if appropriate):
image

image

### CODE REVIEW

**Comment by asherism** [comment]
image
we should map this to sOIL.png and rename to OIL-PERP

**Comment by platschi** [comment]
> image
> avax, matic and oil missing from this table

Also `showPagination` does not seem to work for this table? Seems to be limited to 5 markets, while there are now 7 markets on Kovan. We should decide to either show all 7, or implement the pagination.

**Comment by asherism** [comment]
> > image
> > avax, matic and oil missing from this table
> 
> `showPagination` does not seem to work for this table. Table is limited to 5 markets, while there are now 7 markets on Kovan. We should decide to either show all 7, or implement the pagination.

we should just show all 7

**Comment by asherism** [comment]
image
Asset names missing here- should be "X Perpetual"

**Comment by asherism** [comment]
> image
> 
> Asset names missing here- should be "X Perpetual"

image
same here

**Comment by asherism** [comment]
image
icons showing up in the dropdown but not in the selector itself

**Comment by asherism** [comment]
image
we are still parsing the first letter of the asset in the market info bar

**Review by JChiaramonte7 — APPROVED** [review]

**Pull request merged**
