### PR TITLE
♻️ Futures margin types refactor / cleanup and perps v3 prep

### PR DESCRIPTION
**Pull request by avclarke**
## Description

Initial perps v3 preparations

- Create a perps v3 service on the sdk
- Implement core v3 flows into existing UI
- Refactor the app support perps v3 (cross margin) alongside perps v2 (smart margin)

### CODE REVIEW

**Comment by platschi** [comment]
Screenshot 2023-07-30 at 10 18 11

Application error on connect with MetaMask wallet while on `/dashboard`

**Comment by platschi** [comment]
- [ ] Leaderboard individual trade history not loading

Screenshot 2023-07-30 at 10 20 26

**Comment by platschi** [comment]
- [ ] Transfers tab is back, we removed it in prod. Do we need it for v3? If not, remove.

Screenshot 2023-07-30 at 10 27 18

**Comment by platschi** [comment]
- [ ] Cannot increase position size, even though I have 95 sUSD available. Bug or expected? If the latter, needs warning [if so create new ticket, out of scope]. Decrease works.

Screenshot 2023-07-30 at 10 32 12

**Comment by platschi** [comment]
- [ ] Open Position: Market Margin is 0.00 (should be 83$), TP/SL values are not loaded but should be there (both are set)


### How it is on this PR:
Screenshot 2023-07-30 at 10 37 10


### How it should be (screenshot from prod):
Screenshot 2023-07-30 at 10 38 07

**Comment by avclarke** [comment]
> * [ ]  Cannot increase position size (position size modal), even though I have 95 sUSD available. Decrease works. Value defaults to 0 on input and click on Max
> * [ ]  Same with reduce margin (withdraw margin modal), values default to 0.
> 
> Screenshot 2023-07-30 at 10 32 12

@platschi I can't recreate these but I might have fixed it with a separate change, could you give them another test on the latest commit to check?

**Comment by platschi** [comment]
- When coming from landing page, url shows `?accountType=smart_margin`. When clicking Futures link in the Navigation, it defaults to `?accountType=cross_margin` however.

https://github.com/Kwenta/kwenta/assets/548702/a79c8e67-a857-49c5-a268-5f79e26e0be0

**Review by platschi — APPROVED** [review]

**Pull request merged**
