### PR TITLE
Fix mobile light theme issues

### PR DESCRIPTION
**Pull request by leovct**
There are several small issues on light theme when on responsive mobile view which should be dealt with, in order to officially release light theme support for mobile.

### 1. Navigation
- [x] Add "Menu" text label when hamburger menu is actively selected
Screenshot 2022-10-07 at 10 54 38

- [x] Fix link colors (active/inactive) to something more readable - **already fixed?**
- [x] Fix sub-navigation button background colors - **already fixed?**
Screenshot 2022-10-07 at 16 21 24

### 2. Dashboard
- [x] Headers: Portfolio, Open Positions, Futures Markets yellow-ish is way too bright on mobile _(before/after)_
<p align="center">
  before-better
  Screenshot 2022-10-18 at 01 34 40
</p>

### 3. Markets
- [x] Dropdown menu: Fix PERP price color to be responsive to theme selection, same with change % text color (green/red colors for 24H Change in selected PERP are not aligned with other PERPs in dropdown
Screenshot 2022-10-07 at 11 43 31

- [x] Headers: Fix text-shadow everywhere (same as dashboard): Account, Trade History, Stats, Orders, Trade, Transfers tab, Open Position etc. _(before/after)_
<p align="center">
  Screenshot 2022-10-07 at 15 24 15
  Screenshot 2022-10-07 at 11 47 12
</p>

- [x] Suggestion: Update light theme labels (MarketDetails, MarginInfoBox, FeeBox etc. etc.) to use `#515151` rather than the less accessible `#787878` _(before/after)_
<p align="center">
  Screenshot 2022-10-07 at 11 54 26
  Screenshot 2022-10-07 at 11 54 12
</p>

### 4. Trades & Transfers tabs:
- [x] SHORT/LONG text colors should be updated
Screenshot 2022-10-07 at 15 20 06

- [x] On Transfers tab, text labels are unreadable/not updated to theme colors
Screenshot 2022-10-07 at 13 30 16

### 5. Confirm Order Modal
- [x] Whole modal on mobile still uses dark theme
<p align="center">
  Screenshot 2022-10-07 at 15 52 35
  Screenshot 2022-10-07 at 15 50 57
</p>

### 6. Exchange
- [x] Headers: Fix text-shadow for "From" and "To" (before/after)
<p align="center">
  Screenshot 2022-10-07 at 13 42 57
  Screenshot 2022-10-07 at 13 41 23
</p>

- [x] Update "Swap" button from gold button to new design - **already fixed**
Screenshot 2022-10-07 at 15 29 34

- [x] For quick % selector, when value is selected background is using dark theme setting
**TODO: I could not check if the fix works or not, please confirm!**
- [x] Consider updating labels from #787878 to #515151 for better readability

## Related issue
#1214

### CODE REVIEW

**Comment by asherism** [comment]
image
incorrect drawer separator line color

**Comment by asherism** [comment]
image
all instances of the yellow color on light mode should be updated to the appropriate variation

**Comment by asherism** [comment]
image
active order size button and exchange arrow wrong color

**Comment by platschi** [comment]
- [ ] Navigation: When selecting "Dashboard", and re-visiting the navigation, the active window nav element is white on white, this should be fixed
- [ ] Markets: Radio buttons hide grey border when active
- [ ] Markets: Top Market selector on selection shows top bar with dark theme background
- [ ] Exchange: Active order size selection (25/50/75/100) button not changing
- [ ] Exchange: Into Input value gray when filled in

Generic mobile issues (not relevant for ticket, just noticing for future fixes):

- [ ] Leaderboard: Pinned market shows "1" gold medal, this should not be there. Also rank of connected wallet not shown
- [ ] Exchange: Select Synth modal should be redone on mobile (buggy/unresponsive currently)
- [ ] History: Futures History table shows "hidden" columns when scrolling to the right
- [ ] History: Spot History is not mobile friendly / cut off at "To" field

**Comment by asherism** [comment]
image
dashboard incorrect colors

**Comment by asherism** [comment]
image
settings incorrect colors

**Comment by asherism** [comment]
image
arrow colors should be light mode yellow

**Review by platschi — APPROVED** [review]

**Comment by platschi** [comment]
Moving open issues above into separate ticket

**Pull request merged**
