### PR TITLE
Leaderboard Trader Selection

### PR DESCRIPTION
**Pull request by Tburm**
Add a trader selection to the leaderboard tab.

NOTE: This is a draft until the subgraph syncs

## Description
* Add trader selection
* Add position data to the selection

## Related issue
#376 

## How Has This Been Tested?
Tested positions on the subgraph and checked data between subgraph and UI

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by platschi** [comment]
- We can remove the Leaderboard and Statistics button, as Stats will later go into nav (- #566)

**Comment by JChiaramonte7** [comment]
Two things:

1. Can we vertically align the address?
image

2. We should also push the address to the route when you click on a trader to view their history. Otherwise the back button goes to the dashboard.

**Comment by LeifuChen** [comment]
@Tburm The `StyledSearchInput` is a little bit narrow with the placeholder (so it will be resized when we type the wallet address). Should we add more padding space there?
image

**Review by LeifuChen — APPROVED** [review]
Looks good to me.

**Pull request merged**
