### PR TITLE
feat(i18n): add Persian (Farsi) translation

### PR DESCRIPTION
**Pull request by hanifbirgani**
## Description
This PR adds a complete translation of Kwenta to the Persian (Farsi) language.

## Motivation and Context
I am a Persian speaker, and I'd like to add my language to the Kwenta website to benefit the Kwenta Persian community.

## How Has This Been Tested?
All the changes have been made in a JSON file, so I tested the file using a JSON lint package and the [jsonlint.com](https://jsonlint.com/) online JSON validator service.

### CODE REVIEW

**Comment by hanifbirgani** [comment]
Any feedback on this PR?

**Comment by JChiaramonte7** [comment]
Needs a second persian (farsi) reviewer to audit and make sure the translations are accurate.

cc @platschi can we put out a bounty?

**Comment by platschi** [comment]
@hanifbirgani It would be much appreciated if you can contact me on Discord regarding this PR!

**Comment by platschi** [comment]
Closed for now until further notice

**Pull request closed without merging**
