### PR TITLE
Provide a default provider

### PR DESCRIPTION
**Pull request by bachstatter**
Provide a default provider when not connected

### CODE REVIEW

**Comment by LeifuChen** [comment]
@bachstatter Thanks. However, we get this error in the deployment.
You may check it by yourself: https://kwenta-git-provide-default-provider-kwenta.vercel.app/market/?asset=sETH
image

**Comment by bachstatter** [comment]
Thanks for reporting. Not sure why we're not running into this. I've made a PR to js-monorepo which will fix it.. 
https://github.com/Synthetixio/js-monorepo/pull/277

**Comment by bachstatter** [comment]
@LeifuChen should be fixed now

**Comment by LeifuChen** [comment]
@bachstatter Thanks for the solution. It has been added to #1211.

**Pull request closed without merging**
