### PR TITLE
chore: deprecate Next-price orders

### LINKED ISSUE #1694: Deprecate Next-price orders
### Subject of the issue
Remove the next price orders functionality from isolated margin futures.

Screenshot 2022-11-29 at 12 48 20

### Deliverables

- [x] Remove the option to switch between market and next price on the UI
- [x] Set `isolated margin` futures to "Market" by default
- [x] Clean up next price order related code

### Bounty
200 $OP

### PR DESCRIPTION
**Pull request by abhisheknaiidu**
## Description
 deprecate Next-price orders

## Related issue
fixes #1694

### CODE REVIEW

**Comment by platschi** [comment]
Kindly lint your commits, files have a lot of lint errors/warnings.

**Comment by platschi** [comment]
@abhisheknaiidu error on build:

Screenshot 2022-12-08 at 08 03 18

**Comment by avclarke** [comment]
Changes are looking good @abhisheknaiidu but could you now remove the order type tabs from the `TradeIsolatedMargin` component as there is no need to keep it with only one option to select.

**Comment by platschi** [comment]
@abhisheknaiidu did you manage to have a look at the bug in the screenshot I posted? Maybe it has to do with the conflicting files

**Review by avclarke — APPROVED** [review]
Looks good!

**Comment by platschi** [comment]
Moved to #1784 to avoid dealing with too many conflicting files

**Pull request closed without merging**
